/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SchedulerRouteImport } from './routes/scheduler'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PersonasRouteImport } from './routes/personas'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as GitRouteImport } from './routes/git'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CronJobsRouteImport } from './routes/cron-jobs'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace/index'
import { Route as SpacesIndexRouteImport } from './routes/spaces/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as SeedsIndexRouteImport } from './routes/seeds/index'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as SpacesSpaceIdRouteImport } from './routes/spaces/$spaceId'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions/$sessionId'
import { Route as SeedsSeedIdRouteImport } from './routes/seeds/$seedId'
import { Route as KnowledgeSettingsRouteImport } from './routes/knowledge/settings'
import { Route as KnowledgeHabitsRouteImport } from './routes/knowledge/habits'
import { Route as KnowledgeGraphRouteImport } from './routes/knowledge/graph'
import { Route as AgentsAgentIdRouteImport } from './routes/agents/$agentId'

const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulerRoute = SchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonasRoute = PersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const GitRoute = GitRouteImport.update({
  id: '/git',
  path: '/git',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CronJobsRoute = CronJobsRouteImport.update({
  id: '/cron-jobs',
  path: '/cron-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/workspace/',
  path: '/workspace/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesIndexRoute = SpacesIndexRouteImport.update({
  id: '/spaces/',
  path: '/spaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedsIndexRoute = SeedsIndexRouteImport.update({
  id: '/seeds/',
  path: '/seeds/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesSpaceIdRoute = SpacesSpaceIdRouteImport.update({
  id: '/spaces/$spaceId',
  path: '/spaces/$spaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedsSeedIdRoute = SeedsSeedIdRouteImport.update({
  id: '/seeds/$seedId',
  path: '/seeds/$seedId',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeSettingsRoute = KnowledgeSettingsRouteImport.update({
  id: '/knowledge/settings',
  path: '/knowledge/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeHabitsRoute = KnowledgeHabitsRouteImport.update({
  id: '/knowledge/habits',
  path: '/knowledge/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeGraphRoute = KnowledgeGraphRouteImport.update({
  id: '/knowledge/graph',
  path: '/knowledge/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/budget': typeof BudgetRoute
  '/chat': typeof ChatRoute
  '/cron-jobs': typeof CronJobsRoute
  '/events': typeof EventsRoute
  '/git': typeof GitRoute
  '/marketplace': typeof MarketplaceRoute
  '/memory': typeof MemoryRoute
  '/personas': typeof PersonasRoute
  '/resources': typeof ResourcesRoute
  '/scheduler': typeof SchedulerRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/knowledge/graph': typeof KnowledgeGraphRoute
  '/knowledge/habits': typeof KnowledgeHabitsRoute
  '/knowledge/settings': typeof KnowledgeSettingsRoute
  '/seeds/$seedId': typeof SeedsSeedIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/spaces/$spaceId': typeof SpacesSpaceIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/seeds/': typeof SeedsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/spaces/': typeof SpacesIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/budget': typeof BudgetRoute
  '/chat': typeof ChatRoute
  '/cron-jobs': typeof CronJobsRoute
  '/events': typeof EventsRoute
  '/git': typeof GitRoute
  '/marketplace': typeof MarketplaceRoute
  '/memory': typeof MemoryRoute
  '/personas': typeof PersonasRoute
  '/resources': typeof ResourcesRoute
  '/scheduler': typeof SchedulerRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/knowledge/graph': typeof KnowledgeGraphRoute
  '/knowledge/habits': typeof KnowledgeHabitsRoute
  '/knowledge/settings': typeof KnowledgeSettingsRoute
  '/seeds/$seedId': typeof SeedsSeedIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/spaces/$spaceId': typeof SpacesSpaceIdRoute
  '/agents': typeof AgentsIndexRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/seeds': typeof SeedsIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/spaces': typeof SpacesIndexRoute
  '/workspace': typeof WorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/budget': typeof BudgetRoute
  '/chat': typeof ChatRoute
  '/cron-jobs': typeof CronJobsRoute
  '/events': typeof EventsRoute
  '/git': typeof GitRoute
  '/marketplace': typeof MarketplaceRoute
  '/memory': typeof MemoryRoute
  '/personas': typeof PersonasRoute
  '/resources': typeof ResourcesRoute
  '/scheduler': typeof SchedulerRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/knowledge/graph': typeof KnowledgeGraphRoute
  '/knowledge/habits': typeof KnowledgeHabitsRoute
  '/knowledge/settings': typeof KnowledgeSettingsRoute
  '/seeds/$seedId': typeof SeedsSeedIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/spaces/$spaceId': typeof SpacesSpaceIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/seeds/': typeof SeedsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/spaces/': typeof SpacesIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/budget'
    | '/chat'
    | '/cron-jobs'
    | '/events'
    | '/git'
    | '/marketplace'
    | '/memory'
    | '/personas'
    | '/resources'
    | '/scheduler'
    | '/security'
    | '/settings'
    | '/skills'
    | '/agents/$agentId'
    | '/knowledge/graph'
    | '/knowledge/habits'
    | '/knowledge/settings'
    | '/seeds/$seedId'
    | '/sessions/$sessionId'
    | '/spaces/$spaceId'
    | '/agents/'
    | '/knowledge/'
    | '/seeds/'
    | '/sessions/'
    | '/spaces/'
    | '/workspace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/budget'
    | '/chat'
    | '/cron-jobs'
    | '/events'
    | '/git'
    | '/marketplace'
    | '/memory'
    | '/personas'
    | '/resources'
    | '/scheduler'
    | '/security'
    | '/settings'
    | '/skills'
    | '/agents/$agentId'
    | '/knowledge/graph'
    | '/knowledge/habits'
    | '/knowledge/settings'
    | '/seeds/$seedId'
    | '/sessions/$sessionId'
    | '/spaces/$spaceId'
    | '/agents'
    | '/knowledge'
    | '/seeds'
    | '/sessions'
    | '/spaces'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/budget'
    | '/chat'
    | '/cron-jobs'
    | '/events'
    | '/git'
    | '/marketplace'
    | '/memory'
    | '/personas'
    | '/resources'
    | '/scheduler'
    | '/security'
    | '/settings'
    | '/skills'
    | '/agents/$agentId'
    | '/knowledge/graph'
    | '/knowledge/habits'
    | '/knowledge/settings'
    | '/seeds/$seedId'
    | '/sessions/$sessionId'
    | '/spaces/$spaceId'
    | '/agents/'
    | '/knowledge/'
    | '/seeds/'
    | '/sessions/'
    | '/spaces/'
    | '/workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  BudgetRoute: typeof BudgetRoute
  ChatRoute: typeof ChatRoute
  CronJobsRoute: typeof CronJobsRoute
  EventsRoute: typeof EventsRoute
  GitRoute: typeof GitRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MemoryRoute: typeof MemoryRoute
  PersonasRoute: typeof PersonasRoute
  ResourcesRoute: typeof ResourcesRoute
  SchedulerRoute: typeof SchedulerRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRoute
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
  KnowledgeGraphRoute: typeof KnowledgeGraphRoute
  KnowledgeHabitsRoute: typeof KnowledgeHabitsRoute
  KnowledgeSettingsRoute: typeof KnowledgeSettingsRoute
  SeedsSeedIdRoute: typeof SeedsSeedIdRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  SpacesSpaceIdRoute: typeof SpacesSpaceIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
  SeedsIndexRoute: typeof SeedsIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  SpacesIndexRoute: typeof SpacesIndexRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduler': {
      id: '/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof SchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personas': {
      id: '/personas'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof PersonasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/git': {
      id: '/git'
      path: '/git'
      fullPath: '/git'
      preLoaderRoute: typeof GitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cron-jobs': {
      id: '/cron-jobs'
      path: '/cron-jobs'
      fullPath: '/cron-jobs'
      preLoaderRoute: typeof CronJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/workspace'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/': {
      id: '/spaces/'
      path: '/spaces'
      fullPath: '/spaces/'
      preLoaderRoute: typeof SpacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeds/': {
      id: '/seeds/'
      path: '/seeds'
      fullPath: '/seeds/'
      preLoaderRoute: typeof SeedsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/$spaceId': {
      id: '/spaces/$spaceId'
      path: '/spaces/$spaceId'
      fullPath: '/spaces/$spaceId'
      preLoaderRoute: typeof SpacesSpaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeds/$seedId': {
      id: '/seeds/$seedId'
      path: '/seeds/$seedId'
      fullPath: '/seeds/$seedId'
      preLoaderRoute: typeof SeedsSeedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/settings': {
      id: '/knowledge/settings'
      path: '/knowledge/settings'
      fullPath: '/knowledge/settings'
      preLoaderRoute: typeof KnowledgeSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/habits': {
      id: '/knowledge/habits'
      path: '/knowledge/habits'
      fullPath: '/knowledge/habits'
      preLoaderRoute: typeof KnowledgeHabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/graph': {
      id: '/knowledge/graph'
      path: '/knowledge/graph'
      fullPath: '/knowledge/graph'
      preLoaderRoute: typeof KnowledgeGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  BudgetRoute: BudgetRoute,
  ChatRoute: ChatRoute,
  CronJobsRoute: CronJobsRoute,
  EventsRoute: EventsRoute,
  GitRoute: GitRoute,
  MarketplaceRoute: MarketplaceRoute,
  MemoryRoute: MemoryRoute,
  PersonasRoute: PersonasRoute,
  ResourcesRoute: ResourcesRoute,
  SchedulerRoute: SchedulerRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRoute,
  AgentsAgentIdRoute: AgentsAgentIdRoute,
  KnowledgeGraphRoute: KnowledgeGraphRoute,
  KnowledgeHabitsRoute: KnowledgeHabitsRoute,
  KnowledgeSettingsRoute: KnowledgeSettingsRoute,
  SeedsSeedIdRoute: SeedsSeedIdRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  SpacesSpaceIdRoute: SpacesSpaceIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
  SeedsIndexRoute: SeedsIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  SpacesIndexRoute: SpacesIndexRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
