/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PersonasRouteImport } from './routes/personas'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as GitRouteImport } from './routes/git'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EmailRouteImport } from './routes/email'
import { Route as CronJobsRouteImport } from './routes/cron-jobs'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as A2aRouteImport } from './routes/a2a'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as MountsIndexRouteImport } from './routes/mounts/index'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as AgentGroupsIndexRouteImport } from './routes/agent-groups/index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions/$sessionId'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as KnowledgeSettingsRouteImport } from './routes/knowledge/settings'
import { Route as KnowledgeHabitsRouteImport } from './routes/knowledge/habits'
import { Route as KnowledgeGraphRouteImport } from './routes/knowledge/graph'
import { Route as AgentsAgentIdRouteImport } from './routes/agents/$agentId'
import { Route as AgentGroupsGroupIdRouteImport } from './routes/agent-groups/$groupId'
import { Route as AgentsAgentIdTraceRouteImport } from './routes/agents/$agentId/trace'

const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonasRoute = PersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const GitRoute = GitRouteImport.update({
  id: '/git',
  path: '/git',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const CronJobsRoute = CronJobsRouteImport.update({
  id: '/cron-jobs',
  path: '/cron-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const A2aRoute = A2aRouteImport.update({
  id: '/a2a',
  path: '/a2a',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/workspace/',
  path: '/workspace/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const MountsIndexRoute = MountsIndexRouteImport.update({
  id: '/mounts/',
  path: '/mounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentGroupsIndexRoute = AgentGroupsIndexRouteImport.update({
  id: '/agent-groups/',
  path: '/agent-groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeSettingsRoute = KnowledgeSettingsRouteImport.update({
  id: '/knowledge/settings',
  path: '/knowledge/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeHabitsRoute = KnowledgeHabitsRouteImport.update({
  id: '/knowledge/habits',
  path: '/knowledge/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeGraphRoute = KnowledgeGraphRouteImport.update({
  id: '/knowledge/graph',
  path: '/knowledge/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentGroupsGroupIdRoute = AgentGroupsGroupIdRouteImport.update({
  id: '/agent-groups/$groupId',
  path: '/agent-groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdTraceRoute = AgentsAgentIdTraceRouteImport.update({
  id: '/trace',
  path: '/trace',
  getParentRoute: () => AgentsAgentIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a2a': typeof A2aRoute
  '/approvals': typeof ApprovalsRoute
  '/budget': typeof BudgetRoute
  '/chat': typeof ChatRoute
  '/cron-jobs': typeof CronJobsRoute
  '/email': typeof EmailRoute
  '/events': typeof EventsRoute
  '/git': typeof GitRoute
  '/marketplace': typeof MarketplaceRoute
  '/mcp': typeof McpRoute
  '/memory': typeof MemoryRoute
  '/personas': typeof PersonasRoute
  '/resources': typeof ResourcesRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/agent-groups/$groupId': typeof AgentGroupsGroupIdRoute
  '/agents/$agentId': typeof AgentsAgentIdRouteWithChildren
  '/knowledge/graph': typeof KnowledgeGraphRoute
  '/knowledge/habits': typeof KnowledgeHabitsRoute
  '/knowledge/settings': typeof KnowledgeSettingsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/agent-groups/': typeof AgentGroupsIndexRoute
  '/agents/': typeof AgentsIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/mounts/': typeof MountsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/agents/$agentId/trace': typeof AgentsAgentIdTraceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a2a': typeof A2aRoute
  '/approvals': typeof ApprovalsRoute
  '/budget': typeof BudgetRoute
  '/chat': typeof ChatRoute
  '/cron-jobs': typeof CronJobsRoute
  '/email': typeof EmailRoute
  '/events': typeof EventsRoute
  '/git': typeof GitRoute
  '/marketplace': typeof MarketplaceRoute
  '/mcp': typeof McpRoute
  '/memory': typeof MemoryRoute
  '/personas': typeof PersonasRoute
  '/resources': typeof ResourcesRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/agent-groups/$groupId': typeof AgentGroupsGroupIdRoute
  '/agents/$agentId': typeof AgentsAgentIdRouteWithChildren
  '/knowledge/graph': typeof KnowledgeGraphRoute
  '/knowledge/habits': typeof KnowledgeHabitsRoute
  '/knowledge/settings': typeof KnowledgeSettingsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/agent-groups': typeof AgentGroupsIndexRoute
  '/agents': typeof AgentsIndexRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/mounts': typeof MountsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/agents/$agentId/trace': typeof AgentsAgentIdTraceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a2a': typeof A2aRoute
  '/approvals': typeof ApprovalsRoute
  '/budget': typeof BudgetRoute
  '/chat': typeof ChatRoute
  '/cron-jobs': typeof CronJobsRoute
  '/email': typeof EmailRoute
  '/events': typeof EventsRoute
  '/git': typeof GitRoute
  '/marketplace': typeof MarketplaceRoute
  '/mcp': typeof McpRoute
  '/memory': typeof MemoryRoute
  '/personas': typeof PersonasRoute
  '/resources': typeof ResourcesRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/agent-groups/$groupId': typeof AgentGroupsGroupIdRoute
  '/agents/$agentId': typeof AgentsAgentIdRouteWithChildren
  '/knowledge/graph': typeof KnowledgeGraphRoute
  '/knowledge/habits': typeof KnowledgeHabitsRoute
  '/knowledge/settings': typeof KnowledgeSettingsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/agent-groups/': typeof AgentGroupsIndexRoute
  '/agents/': typeof AgentsIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/mounts/': typeof MountsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/agents/$agentId/trace': typeof AgentsAgentIdTraceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a2a'
    | '/approvals'
    | '/budget'
    | '/chat'
    | '/cron-jobs'
    | '/email'
    | '/events'
    | '/git'
    | '/marketplace'
    | '/mcp'
    | '/memory'
    | '/personas'
    | '/resources'
    | '/security'
    | '/settings'
    | '/skills'
    | '/agent-groups/$groupId'
    | '/agents/$agentId'
    | '/knowledge/graph'
    | '/knowledge/habits'
    | '/knowledge/settings'
    | '/projects/$projectId'
    | '/sessions/$sessionId'
    | '/agent-groups/'
    | '/agents/'
    | '/knowledge/'
    | '/mounts/'
    | '/projects/'
    | '/sessions/'
    | '/workspace/'
    | '/agents/$agentId/trace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a2a'
    | '/approvals'
    | '/budget'
    | '/chat'
    | '/cron-jobs'
    | '/email'
    | '/events'
    | '/git'
    | '/marketplace'
    | '/mcp'
    | '/memory'
    | '/personas'
    | '/resources'
    | '/security'
    | '/settings'
    | '/skills'
    | '/agent-groups/$groupId'
    | '/agents/$agentId'
    | '/knowledge/graph'
    | '/knowledge/habits'
    | '/knowledge/settings'
    | '/projects/$projectId'
    | '/sessions/$sessionId'
    | '/agent-groups'
    | '/agents'
    | '/knowledge'
    | '/mounts'
    | '/projects'
    | '/sessions'
    | '/workspace'
    | '/agents/$agentId/trace'
  id:
    | '__root__'
    | '/'
    | '/a2a'
    | '/approvals'
    | '/budget'
    | '/chat'
    | '/cron-jobs'
    | '/email'
    | '/events'
    | '/git'
    | '/marketplace'
    | '/mcp'
    | '/memory'
    | '/personas'
    | '/resources'
    | '/security'
    | '/settings'
    | '/skills'
    | '/agent-groups/$groupId'
    | '/agents/$agentId'
    | '/knowledge/graph'
    | '/knowledge/habits'
    | '/knowledge/settings'
    | '/projects/$projectId'
    | '/sessions/$sessionId'
    | '/agent-groups/'
    | '/agents/'
    | '/knowledge/'
    | '/mounts/'
    | '/projects/'
    | '/sessions/'
    | '/workspace/'
    | '/agents/$agentId/trace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  A2aRoute: typeof A2aRoute
  ApprovalsRoute: typeof ApprovalsRoute
  BudgetRoute: typeof BudgetRoute
  ChatRoute: typeof ChatRoute
  CronJobsRoute: typeof CronJobsRoute
  EmailRoute: typeof EmailRoute
  EventsRoute: typeof EventsRoute
  GitRoute: typeof GitRoute
  MarketplaceRoute: typeof MarketplaceRoute
  McpRoute: typeof McpRoute
  MemoryRoute: typeof MemoryRoute
  PersonasRoute: typeof PersonasRoute
  ResourcesRoute: typeof ResourcesRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRoute
  AgentGroupsGroupIdRoute: typeof AgentGroupsGroupIdRoute
  AgentsAgentIdRoute: typeof AgentsAgentIdRouteWithChildren
  KnowledgeGraphRoute: typeof KnowledgeGraphRoute
  KnowledgeHabitsRoute: typeof KnowledgeHabitsRoute
  KnowledgeSettingsRoute: typeof KnowledgeSettingsRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  AgentGroupsIndexRoute: typeof AgentGroupsIndexRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
  MountsIndexRoute: typeof MountsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personas': {
      id: '/personas'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof PersonasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/git': {
      id: '/git'
      path: '/git'
      fullPath: '/git'
      preLoaderRoute: typeof GitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cron-jobs': {
      id: '/cron-jobs'
      path: '/cron-jobs'
      fullPath: '/cron-jobs'
      preLoaderRoute: typeof CronJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a2a': {
      id: '/a2a'
      path: '/a2a'
      fullPath: '/a2a'
      preLoaderRoute: typeof A2aRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/workspace'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mounts/': {
      id: '/mounts/'
      path: '/mounts'
      fullPath: '/mounts/'
      preLoaderRoute: typeof MountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-groups/': {
      id: '/agent-groups/'
      path: '/agent-groups'
      fullPath: '/agent-groups/'
      preLoaderRoute: typeof AgentGroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/settings': {
      id: '/knowledge/settings'
      path: '/knowledge/settings'
      fullPath: '/knowledge/settings'
      preLoaderRoute: typeof KnowledgeSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/habits': {
      id: '/knowledge/habits'
      path: '/knowledge/habits'
      fullPath: '/knowledge/habits'
      preLoaderRoute: typeof KnowledgeHabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/graph': {
      id: '/knowledge/graph'
      path: '/knowledge/graph'
      fullPath: '/knowledge/graph'
      preLoaderRoute: typeof KnowledgeGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-groups/$groupId': {
      id: '/agent-groups/$groupId'
      path: '/agent-groups/$groupId'
      fullPath: '/agent-groups/$groupId'
      preLoaderRoute: typeof AgentGroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId/trace': {
      id: '/agents/$agentId/trace'
      path: '/trace'
      fullPath: '/agents/$agentId/trace'
      preLoaderRoute: typeof AgentsAgentIdTraceRouteImport
      parentRoute: typeof AgentsAgentIdRoute
    }
  }
}

interface AgentsAgentIdRouteChildren {
  AgentsAgentIdTraceRoute: typeof AgentsAgentIdTraceRoute
}

const AgentsAgentIdRouteChildren: AgentsAgentIdRouteChildren = {
  AgentsAgentIdTraceRoute: AgentsAgentIdTraceRoute,
}

const AgentsAgentIdRouteWithChildren = AgentsAgentIdRoute._addFileChildren(
  AgentsAgentIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  A2aRoute: A2aRoute,
  ApprovalsRoute: ApprovalsRoute,
  BudgetRoute: BudgetRoute,
  ChatRoute: ChatRoute,
  CronJobsRoute: CronJobsRoute,
  EmailRoute: EmailRoute,
  EventsRoute: EventsRoute,
  GitRoute: GitRoute,
  MarketplaceRoute: MarketplaceRoute,
  McpRoute: McpRoute,
  MemoryRoute: MemoryRoute,
  PersonasRoute: PersonasRoute,
  ResourcesRoute: ResourcesRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRoute,
  AgentGroupsGroupIdRoute: AgentGroupsGroupIdRoute,
  AgentsAgentIdRoute: AgentsAgentIdRouteWithChildren,
  KnowledgeGraphRoute: KnowledgeGraphRoute,
  KnowledgeHabitsRoute: KnowledgeHabitsRoute,
  KnowledgeSettingsRoute: KnowledgeSettingsRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  AgentGroupsIndexRoute: AgentGroupsIndexRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
  MountsIndexRoute: MountsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
